# Generated by Django 3.1.1 on 2020-10-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('referance', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Chimica_Generale',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('ATM', 'Teoria Atomica e Proprietà Periodiche'), ('ACB', 'Teorie del pH e tamponi')], default='ACB', max_length=3)),
                ('sistema', models.TextField()),
                ('commento', models.TextField()),
                ('risultato', models.TextField()),
            ],
            bases=('Exercises.exercise',),
        ),
        migrations.CreateModel(
            name='Chimica_Organica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('SIN', 'Sintesi'), ('CAN', 'Alcani'), ('CHE', 'Alcani'), ('CHI', 'Alcheni'), ('PHS', 'Aromatici'), ('RCO', 'Carbonile')], default='SIN', max_length=3)),
                ('strutture', models.FileField(upload_to='')),
                ('meccanismo', models.FileField(blank=True, upload_to='')),
                ('commento', models.TextField()),
            ],
            bases=('Exercises.exercise',),
        ),
        migrations.CreateModel(
            name='Matematica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('MAT', 'Matrici'), ('FUN', 'Studio di funzioni')], default='MAT', max_length=3)),
                ('dimostrazione', models.TextField()),
                ('grafico', models.FileField(blank=True, upload_to='')),
            ],
            bases=('Exercises.exercise',),
        ),
    ]
