# Generated by Django 3.1.1 on 2020-10-03 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chimica_Fisica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('GAS', 'Teorie dei gas'), ('THM', 'Termodinamica e termochimica'), ('ELE', 'Elettrodi')], default='GAS', max_length=3)),
                ('sistema', models.TextField()),
                ('commento', models.TextField()),
                ('risultato', models.TextField()),
            ],
            bases=('Exercises.exercise',),
        ),
        migrations.CreateModel(
            name='Chimica_Generale_Analitica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('ATM', 'Teoria Atomica e Proprietà Periodiche'), ('ACB', 'Teorie del pH e tamponi'), ('RED', 'Reazioni redox'), ('ELE', 'Elettrochimica')], default='ACB', max_length=3)),
                ('sistema', models.TextField()),
                ('commento', models.TextField()),
                ('risultato', models.TextField()),
            ],
            bases=('Exercises.exercise',),
        ),
        migrations.DeleteModel(
            name='Chimica_Generale',
        ),
    ]
