# Generated by Django 3.1.1 on 2020-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0002_auto_20201003_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.TextField(default='Draft'),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='argomento',
            field=models.CharField(choices=[('ELE', 'Elettrodi'), ('GAS', 'Teorie dei gas'), ('THM', 'Termodinamica e termochimica')], default='GAS', max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='argomento',
            field=models.CharField(choices=[('ELE', 'Elettrochimica'), ('RED', 'Reazioni redox'), ('ATM', 'Teoria Atomica e Proprietà Periodiche'), ('ACB', 'Teorie del pH e tamponi')], default='ACB', max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_organica',
            name='argomento',
            field=models.CharField(choices=[('CAN', 'Alcani'), ('CHE', 'Alcheni'), ('CHI', 'Alchini'), ('PHS', 'Aromatici'), ('RCO', 'Carbonile'), ('SIN', 'Sintesi')], default='SIN', max_length=3),
        ),
    ]
