# Generated by Django 3.1.1 on 2020-10-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0003_auto_20201004_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='status',
            field=models.CharField(default='Draft', editable=False, max_length=10),
        ),
    ]
