# Generated by Django 3.1.1 on 2020-10-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0004_auto_20201004_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matematica',
            old_name='dimostrazione',
            new_name='dim',
        ),
    ]
