# Generated by Django 3.1.1 on 2020-10-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0005_auto_20201004_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chimica_generale_analitica',
            name='exercise_ptr',
        ),
        migrations.RemoveField(
            model_name='chimica_organica',
            name='exercise_ptr',
        ),
        migrations.RemoveField(
            model_name='matematica',
            name='exercise_ptr',
        ),
        migrations.DeleteModel(
            name='Chimica_Fisica',
        ),
        migrations.DeleteModel(
            name='Chimica_Generale_Analitica',
        ),
        migrations.DeleteModel(
            name='Chimica_Organica',
        ),
        migrations.DeleteModel(
            name='Matematica',
        ),
    ]
