# Generated by Django 3.1.1 on 2020-10-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0006_auto_20201006_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chimica_Fisica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('ELE', 'Elettrodi'), ('GAS', 'Teorie dei gas'), ('THM', 'Termodinamica e termochimica')], default='GAS', max_length=3)),
                ('sistema', models.TextField()),
                ('commento', models.TextField()),
                ('risultato', models.TextField()),
            ],
            bases=('Exercises.exercise',),
        ),
        migrations.CreateModel(
            name='Chimica_Generale_Analitica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('ELE', 'Elettrochimica'), ('RED', 'Reazioni redox'), ('ATM', 'Teoria Atomica e Proprietà Periodiche'), ('ACB', 'Teorie del pH e tamponi')], default='ACB', max_length=3)),
                ('sistema', models.TextField()),
                ('commento', models.TextField()),
                ('risultato', models.TextField()),
            ],
            bases=('Exercises.exercise',),
        ),
        migrations.CreateModel(
            name='Chimica_Organica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('CAN', 'Alcani'), ('CHE', 'Alcheni'), ('CHI', 'Alchini'), ('PHS', 'Aromatici'), ('RCO', 'Carbonile'), ('SIN', 'Sintesi')], default='SIN', max_length=3)),
                ('strutture', models.FileField(upload_to='')),
                ('meccanismo', models.FileField(blank=True, upload_to='')),
                ('commento', models.TextField()),
            ],
            bases=('Exercises.exercise',),
        ),
        migrations.CreateModel(
            name='Matematica',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Exercises.exercise')),
                ('argomento', models.CharField(choices=[('MAT', 'Matrici'), ('FUN', 'Studio di funzioni')], default='MAT', max_length=3)),
                ('dim', models.TextField()),
                ('grafico', models.FileField(blank=True, upload_to='')),
            ],
            bases=('Exercises.exercise',),
        ),
    ]
