# Generated by Django 3.1.1 on 2020-10-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Exercises', '0007_chimica_fisica_chimica_generale_analitica_chimica_organica_matematica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chimica_fisica',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='chimica_generale_analitica',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='chimica_organica',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='matematica',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_exercises.exercise_set+', to='contenttypes.contenttype'),
        ),
    ]
