# Generated by Django 3.1.1 on 2020-10-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0008_auto_20201006_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chimica_generale_analitica',
            options={},
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='argomento',
            field=models.CharField(choices=[('GAS', 'Teorie dei gas'), ('THM', 'Termodinamica e termochimica'), ('KIN', 'Cinetica chimica'), ('ELE', 'Elettrodi')], default='GAS', max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='argomento',
            field=models.CharField(choices=[('ATM', '1. Teoria atomica e Proprietà periodiche'), ('REA', '2. Reazioni chimiche'), ('STE', '3. Stechiometria'), ('PTH', '4. Principi di termochimica'), ('BON', '5. Legami chimici'), ('SOL', '6. Soluzioni e concentrazioni'), ('COL', '7. Proprietà colligative'), ('ACB', '8. Teorie del pH e tamponi'), ('RED', '9. Reazioni redox')], help_text="Selezionare l'argomento di appartenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='commento',
            field=models.TextField(help_text='Commentare il processo mentale che ha portato alla scrittura delle varie equazioni utilizzate facendo riferminto.'),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='risultato',
            field=models.TextField(help_text='Evidenziare il risultato ottenuto dalla risoluzione delle equazioni.'),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='sistema',
            field=models.TextField(help_text='Scrivere qui le varie equazioni utilizzate per risolvere il problema. Possibilmente numerarle.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='referance',
            field=models.TextField(help_text='Se è un libro: Cognome N., Titolo del testo, Casa editrice, anno di pubblicazione con edizione, pagina. Se è un sito inserire il link'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(help_text='NON MODIFICARE'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.TextField(help_text='Scrivere il testo del problema. Se si è utilizzato il bot che sfrutta la tecnologia OCR controllare la correttezza del teso ricevuto.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(help_text='Inserire un titolo esplicativo', max_length=120),
        ),
    ]
