# Generated by Django 3.1.1 on 2020-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0009_auto_20201008_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chimica_fisica',
            options={'verbose_name': 'Chimica Fisica', 'verbose_name_plural': 'Chimica Fisica'},
        ),
        migrations.AlterModelOptions(
            name='chimica_generale_analitica',
            options={'verbose_name': 'Chimica Generale ed Analitica', 'verbose_name_plural': 'Chimica Generale ed Analitica'},
        ),
        migrations.AlterModelOptions(
            name='chimica_organica',
            options={'verbose_name': 'Chimica Organica', 'verbose_name_plural': 'Chimica Organica'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Esercizio', 'verbose_name_plural': 'Esercizi'},
        ),
        migrations.AlterModelOptions(
            name='matematica',
            options={'verbose_name': 'Matematica', 'verbose_name_plural': 'Matematica'},
        ),
        migrations.AddField(
            model_name='matematica',
            name='commento',
            field=models.TextField(default='test', help_text='Commentare il processo mentale che ha portato alla scelta di ciò che è stato caricato come "struttura" e nell\'eventuale meccanismo.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matematica',
            name='risultato',
            field=models.TextField(blank=True, help_text='Evidenziare il risultato ottenuto dalla risoluzione delle equazioni.'),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='argomento',
            field=models.CharField(choices=[('GAS', '1. Teorie dei gas'), ('THD', '2. Termodinamica'), ('THC', '3. Termochimica'), ('KIN', '4. Cinetica chimica'), ('ELE', '5. Elettrodi')], help_text="Selezionare l'argomento di appartenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='commento',
            field=models.TextField(help_text='Commentare il processo mentale che ha portato alla scrittura delle varie equazioni utilizzate facendo riferminto.'),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='risultato',
            field=models.TextField(help_text='Evidenziare il risultato ottenuto dalla risoluzione delle equazioni.'),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='sistema',
            field=models.TextField(help_text='Scrivere qui le varie equazioni utilizzate per risolvere il problema. Possibilmente numerarle.'),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='argomento',
            field=models.CharField(choices=[('INT', '0. Nomenclatura e Cifre significative'), ('STE', '1. Stechiometria'), ('ATM', '2. Teoria atomica e Proprietà periodiche'), ('REA', '3. Reazioni chimiche'), ('PTH', '4. Principi di termochimica'), ('BON', '5. Legami chimici'), ('SOL', '6. Soluzioni e concentrazioni'), ('COL', '7. Proprietà colligative'), ('ACB', '8. Teorie del pH e tamponi'), ('RED', '9. Reazioni redox')], help_text="Selezionare l'argomento di appartenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_organica',
            name='argomento',
            field=models.CharField(choices=[('CAN', '1. Alcani'), ('CHE', '2. Alcheni'), ('CHI', '3. Alchini'), ('PHS', '4. Aromatici'), ('ALO', '5. Alogenoderivati'), ('ALC', '5. Alcoli e Tioli'), ('AMM', '6. Ammine'), ('RCO', '7. Carbonile'), ('SIN', '8. Sintesi')], help_text="Selezionare l'argomento di appartenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_organica',
            name='commento',
            field=models.TextField(help_text='Commentare il processo mentale che ha portato alla scelta di ciò che è stato caricato come "struttura" e nell\'eventuale meccanismo.'),
        ),
        migrations.AlterField(
            model_name='chimica_organica',
            name='meccanismo',
            field=models.ImageField(blank=True, help_text="Caricare un file .png/.svg/.jpeg contenente lo schema dell'eventuale meccanismo di reazione", upload_to=''),
        ),
        migrations.AlterField(
            model_name='chimica_organica',
            name='strutture',
            field=models.ImageField(help_text='Caricare un file .png/.svg/.jpeg contenente lo schema della reazione', upload_to='str/'),
        ),
        migrations.AlterField(
            model_name='matematica',
            name='argomento',
            field=models.CharField(choices=[('NRE', '1. Numeri reali'), ('COM', '2. Numeri complessi'), ('EUC', '3. Lo spazio euclideo \\(R^n\\)'), ('TOP', '4. Topologia di \\(R^n\\)'), ('ASI', '5. Confronto asintotico'), ('SER', '6. Serie'), ('SEP', '7. Serie di potenze'), ('DER', '8. Derivate'), ('FEL', '9. Funzioni elemntari'), ('ACO', '10. Argomento di un numero complesso'), ('INT', '11. Primitive ed integrali'), ('SSE', '12. Sviluppi in serie'), ('INI', '13. Integrali impropi')], help_text="Selezionare l'argomento di appartenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='matematica',
            name='dim',
            field=models.TextField(help_text="Scrivere la dimostrazione per risolvere il problema. È pensato anche come entry per definire l'eventuale sistema di equazioni per risolvere il problema."),
        ),
        migrations.AlterField(
            model_name='matematica',
            name='grafico',
            field=models.FileField(blank=True, help_text="Caricare un file .png/.svg/.jpeg contenente l'eventuale grafico necessario per la dimostrazione", upload_to=''),
        ),
    ]
