# Generated by Django 3.1.1 on 2020-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0010_auto_20201019_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chimica_organica',
            name='meccanismo',
            field=models.ImageField(blank=True, help_text="Caricare un file .png/.svg/.jpeg contenente lo schema dell'eventuale meccanismo di reazione", upload_to='mech/'),
        ),
        migrations.AlterField(
            model_name='matematica',
            name='grafico',
            field=models.ImageField(blank=True, help_text="Caricare un file .png/.svg/.jpeg contenente l'eventuale grafico necessario per la dimostrazione", upload_to='graphs'),
        ),
    ]
