# Generated by Django 3.1.1 on 2020-10-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercises', '0011_auto_20201020_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='chimica_fisica',
            name='grafico',
            field=models.ImageField(blank=True, help_text="Caricare un file .png/.svg/.jpeg contenente l'eventuale grafico necessario.", upload_to='graphs'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='fig',
            field=models.ImageField(blank=True, help_text="Carica un'eventuale immagine che completi il testo dell'esercizio", null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='argomento',
            field=models.CharField(choices=[('GAS', '1. Teorie dei gas'), ('THD', '2. Termodinamica'), ('THC', '3. Termochimica'), ('KIN', '4. Cinetica chimica'), ('ELE', '5. Elettrodi')], help_text="Selezionare l'argomento di appartenenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='commento',
            field=models.TextField(help_text='Commentare il processo mentale che ha portato alla scrittura delle varie equazioni utilizzate facendo rifermento.'),
        ),
        migrations.AlterField(
            model_name='chimica_fisica',
            name='sistema',
            field=models.TextField(blank=True, help_text='Scrivere qui le varie equazioni utilizzate per risolvere il problema. Possibilmente numerarle.'),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='argomento',
            field=models.CharField(choices=[('INT', '0. Nomenclatura e Cifre significative'), ('STE', '1. Stechiometria'), ('ATM', '2. Teoria atomica e Proprietà periodiche'), ('REA', '3. Reazioni chimiche'), ('PTH', '4. Principi di termochimica'), ('BON', '5. Legami chimici'), ('SOL', '6. Soluzioni e concentrazioni'), ('COL', '7. Proprietà colligative'), ('ACB', '8. Teorie del pH e tamponi'), ('RED', '9. Reazioni redox')], help_text="Selezionare l'argomento di appartenenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='chimica_generale_analitica',
            name='commento',
            field=models.TextField(help_text='Commentare il processo mentale che ha portato alla scrittura delle varie equazioni utilizzate facendo rifermento.'),
        ),
        migrations.AlterField(
            model_name='chimica_organica',
            name='argomento',
            field=models.CharField(choices=[('CAN', '1. Alcani'), ('CHE', '2. Alcheni'), ('CHI', '3. Alchini'), ('PHS', '4. Aromatici'), ('ALO', '5. Alogenoderivati'), ('ALC', '5. Alcoli e Tioli'), ('AMM', '6. Ammine'), ('RCO', '7. Carbonile'), ('SIN', '8. Sintesi')], help_text="Selezionare l'argomento di appartenenza dell'esercizio", max_length=3),
        ),
        migrations.AlterField(
            model_name='matematica',
            name='argomento',
            field=models.CharField(choices=[('NRE', '1. Numeri reali'), ('COM', '2. Numeri complessi'), ('EUC', '3. Lo spazio euclideo \\(R^n\\)'), ('TOP', '4. Topologia di \\(R^n\\)'), ('ASI', '5. Confronto asintotico'), ('SER', '6. Serie'), ('SEP', '7. Serie di potenze'), ('DER', '8. Derivate'), ('FEL', '9. Funzioni elemntari'), ('ACO', '10. Argomento di un numero complesso'), ('INT', '11. Primitive ed integrali'), ('SSE', '12. Sviluppi in serie'), ('INI', '13. Integrali impropi')], help_text="Selezionare l'argomento di appartenenza dell'esercizio", max_length=3),
        ),
    ]
